--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-02-2024   
--------------------------------------------------------
DROP TABLE "ELLAJDBC"."MEMBER_TBL" cascade constraints;
DROP TABLE "ELLAJDBC"."MEMBER_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "ELLAJDBC"."MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(30 BYTE), 
	"GENDER" VARCHAR2(6 BYTE), 
	"AGE" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(12 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"HOBBY" VARCHAR2(300 BYTE), 
	"REG_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ELLAJDBC.MEMBER_TBL
SET DEFINE OFF;
Insert into ELLAJDBC.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,REG_DATE) values ('1','2','1','1',1,'2','2','2','2',to_date('24/07/01','RR/MM/DD'));
Insert into ELLAJDBC.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,REG_DATE) values ('khuser06','pass06','육용자','여',66,'khuser06@kh.com','01083839494','서울시 남대문구','독서, 수영',to_date('24/07/01','RR/MM/DD'));
Insert into ELLAJDBC.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,REG_DATE) values ('khuser02','pass02','이용자','남',27,'khuser02@kh.com','01054532710','dsfmsdm','df',to_date('24/07/01','RR/MM/DD'));
Insert into ELLAJDBC.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,REG_DATE) values ('khuser07','pass07','칠용자','여',77,'khuser07@kh.com','01045875423','dkj','dirn',to_date('24/07/01','RR/MM/DD'));
Insert into ELLAJDBC.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,REG_DATE) values ('khuser01','pass01','일용자','여',21,'khuser01@kh.com','01038776565','상도로 808','농구놀이',to_date('24/07/01','RR/MM/DD'));
Insert into ELLAJDBC.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,REG_DATE) values ('khuser03','pass03','삼용자','남',19,'khuser03@kh.com','01078457523','dsfmsdm','df',to_date('24/07/01','RR/MM/DD'));
Insert into ELLAJDBC.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,REG_DATE) values ('khuser04','pass04','사용자','여',23,'khuser04@kh.com','01080442247','dsfmsdm','df',to_date('24/07/01','RR/MM/DD'));
Insert into ELLAJDBC.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_NAME,GENDER,AGE,EMAIL,PHONE,ADDRESS,HOBBY,REG_DATE) values ('khuser05','pass05','오용자','남',28,'khuser05@kh.com','01003278541','dsfmsdm','df',to_date('24/07/01','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007265
--------------------------------------------------------

  CREATE UNIQUE INDEX "ELLAJDBC"."SYS_C007265" ON "ELLAJDBC"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "ELLAJDBC"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ELLAJDBC"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ELLAJDBC"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
